# Generated by Django 4.1.10 on 2024-05-16 16:32

import ailla.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('islandora_pid', models.CharField(blank=True, max_length=20, null=True)),
                ('legacy_id', models.CharField(blank=True, max_length=20, null=True)),
                ('indigenous_title', models.TextField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('indigenous_description', models.TextField(blank=True, null=True)),
                ('fedora_uuid', models.CharField(max_length=300)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('draft', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContributorRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('islandora_pid', models.CharField(blank=True, max_length=20, null=True)),
                ('country_code', models.CharField(blank=True, max_length=10, null=True)),
                ('viaf', models.URLField(blank=True, null=True)),
                ('flag_code', models.CharField(blank=True, max_length=3, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Folders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('islandora_pid', models.CharField(blank=True, max_length=20, null=True)),
                ('legacy_id', models.CharField(blank=True, max_length=20, null=True)),
                ('indigenous_title', models.TextField(blank=True)),
                ('indigenous_description', models.TextField(blank=True)),
                ('language_community', models.TextField(blank=True)),
                ('fedora_uuid', models.CharField(max_length=300)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('draft', models.BooleanField(default=True)),
                ('sip', models.CharField(blank=True, max_length=300, null=True)),
                ('countries', models.ManyToManyField(blank=True, to='ailla.countries')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('islandora_pid', models.CharField(blank=True, max_length=20, null=True)),
                ('indigenous_name', models.CharField(blank=True, max_length=300, null=True)),
                ('alternative_name', models.CharField(blank=True, max_length=300, null=True)),
                ('language_code', models.CharField(blank=True, max_length=5, null=True)),
                ('macro_language', models.BooleanField()),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('countries', models.ManyToManyField(blank=True, to='ailla.countries')),
            ],
        ),
        migrations.CreateModel(
            name='Organizations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('islandora_pid', models.CharField(blank=True, max_length=20, null=True)),
                ('acronym', models.CharField(blank=True, max_length=20, null=True)),
                ('director_names', models.JSONField(blank=True, default=dict)),
                ('funder', models.CharField(blank=True, max_length=300, null=True)),
                ('parent_institution', models.CharField(blank=True, max_length=300, null=True)),
                ('depositor_status', models.BooleanField()),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en', models.TextField(blank=True)),
                ('es', models.TextField(blank=True)),
                ('pt', models.TextField(blank=True)),
                ('en_neutral', models.CharField(blank=True, max_length=300, null=True)),
                ('es_neutral', models.CharField(blank=True, max_length=300, null=True)),
                ('pt_neutral', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliation', models.CharField(blank=True, max_length=256, null=True)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('country', models.CharField(blank=True, max_length=256, null=True)),
                ('role', models.CharField(choices=[('SUPER', 'SuperAdmin'), ('ADMIN', 'Admin'), ('USER', 'User')], default='USER', max_length=5)),
                ('verified', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('disabled', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='title', to='ailla.text')),
                ('uri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uri', to='ailla.text')),
            ],
        ),
        migrations.CreateModel(
            name='Persons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('islandora_pid', models.CharField(blank=True, max_length=20, null=True)),
                ('given_name', models.CharField(blank=True, max_length=60, null=True)),
                ('surname', models.CharField(blank=True, max_length=60, null=True)),
                ('birth_year', models.IntegerField(blank=True, null=True)),
                ('alternative_names', models.JSONField(blank=True, default=dict, null=True)),
                ('place_of_origin', models.CharField(blank=True, max_length=300, null=True)),
                ('depositor_status', models.BooleanField()),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('description', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ailla.text')),
                ('native_languages', models.ManyToManyField(blank=True, related_name='native_languages', to='ailla.languages')),
                ('organizations', models.ManyToManyField(to='ailla.organizations')),
                ('other_languages', models.ManyToManyField(related_name='other_languages', to='ailla.languages')),
                ('research_languages', models.ManyToManyField(related_name='research_languages', to='ailla.languages')),
                ('user_last_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles_description', to='ailla.text')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles_name', to='ailla.text')),
            ],
        ),
        migrations.CreateModel(
            name='OriginalMediaType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='og_media_description', to='ailla.text')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='og_media_name', to='ailla.text')),
            ],
        ),
        migrations.AddField(
            model_name='organizations',
            name='description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_description', to='ailla.text'),
        ),
        migrations.AddField(
            model_name='organizations',
            name='org_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_name', to='ailla.text'),
        ),
        migrations.AddField(
            model_name='organizations',
            name='research_languages',
            field=models.ManyToManyField(to='ailla.languages'),
        ),
        migrations.AddField(
            model_name='organizations',
            name='user_last_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MediaContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_description', to='ailla.text')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_name', to='ailla.text')),
            ],
        ),
        migrations.AddField(
            model_name='languages',
            name='description',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lang_description', to='ailla.text'),
        ),
        migrations.AddField(
            model_name='languages',
            name='language_family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ailla.languages'),
        ),
        migrations.AddField(
            model_name='languages',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lang_name', to='ailla.text'),
        ),
        migrations.AddField(
            model_name='languages',
            name='user_last_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('islandora_pid', models.CharField(blank=True, max_length=20, null=True)),
                ('legacy_id', models.CharField(blank=True, max_length=20, null=True)),
                ('indigenous_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('indigenous_description', models.TextField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('fedora_uuid', models.CharField(max_length=300)),
                ('visibility', models.CharField(choices=[('PUB', 'Public'), ('LOG', 'Login'), ('RST', 'Restricted'), ('DRA', 'Draft'), ('EMB', 'Embargoed')], default='DRA', max_length=3)),
                ('embargo_date', models.DateField(blank=True, default=None, null=True)),
                ('date_created', models.IntegerField(blank=True, null=True)),
                ('draft', models.BooleanField(default=True)),
                ('update_manifest', models.BooleanField(default=False)),
                ('contributor_orgs', models.ManyToManyField(blank=True, related_name='org_items', through='ailla.ContributorRole', to='ailla.organizations')),
                ('contributor_persons', models.ManyToManyField(blank=True, related_name='person_items', through='ailla.ContributorRole', to='ailla.persons')),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ailla.text')),
                ('genre', models.ManyToManyField(blank=True, to='ailla.genre')),
                ('lang_indigenous_description', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_lang_indigenous_desc', to='ailla.languages')),
                ('lang_indigenous_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ailla.languages')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_name', to='ailla.text')),
                ('parent_folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ailla.folders')),
                ('user_last_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='genre',
            name='description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genre_description', to='ailla.text'),
        ),
        migrations.AddField(
            model_name='genre',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genre_name', to='ailla.text'),
        ),
        migrations.AddField(
            model_name='folders',
            name='description',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ailla.text'),
        ),
        migrations.AddField(
            model_name='folders',
            name='lang_indigenous_description',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folder_lang_indigenous_description', to='ailla.languages'),
        ),
        migrations.AddField(
            model_name='folders',
            name='lang_indigenous_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ailla.languages'),
        ),
        migrations.AddField(
            model_name='folders',
            name='parent_collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='ailla.collections'),
        ),
        migrations.AddField(
            model_name='folders',
            name='subject_languages',
            field=models.ManyToManyField(blank=True, related_name='subject_languages', to='ailla.languages'),
        ),
        migrations.AddField(
            model_name='folders',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folder_title', to='ailla.text'),
        ),
        migrations.AddField(
            model_name='folders',
            name='user_last_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('islandora_pid', models.CharField(blank=True, max_length=20, null=True)),
                ('legacy_id', models.CharField(blank=True, max_length=20, null=True)),
                ('filename', models.CharField(blank=True, max_length=256)),
                ('source_note', models.TextField(blank=True)),
                ('place_created', models.TextField(blank=True)),
                ('media_type', models.CharField(blank=True, max_length=30)),
                ('tape_label', models.CharField(blank=True, max_length=60)),
                ('date_uploaded', models.DateTimeField(default=ailla.models.get_current_date)),
                ('date_modified', models.DateTimeField(default=ailla.models.get_current_date)),
                ('date_archived', models.DateTimeField(blank=True, null=True)),
                ('date_created', models.IntegerField(blank=True, null=True)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('extent', models.CharField(blank=True, max_length=10, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('fedora_uuid', models.CharField(blank=True, max_length=300)),
                ('fedora_hash_location', models.TextField(blank=True, null=True)),
                ('rights_statement_note', models.TextField(blank=True, null=True)),
                ('upload_status', models.IntegerField(default=-1)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ailla.mediacontenttype')),
                ('media_language', models.ManyToManyField(blank=True, related_name='media_language_files', to='ailla.languages')),
                ('original_medium', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ailla.originalmediatype')),
                ('parent_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='ailla.items')),
                ('rights_statements', models.ManyToManyField(blank=True, related_name='rights_statements', to='ailla.rights')),
            ],
        ),
        migrations.AddField(
            model_name='countries',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ailla.text'),
        ),
        migrations.AddField(
            model_name='countries',
            name='user_last_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contributorrole',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ailla.items'),
        ),
        migrations.AddField(
            model_name='contributorrole',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ailla.organizations'),
        ),
        migrations.AddField(
            model_name='contributorrole',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ailla.persons'),
        ),
        migrations.AddField(
            model_name='contributorrole',
            name='role_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ailla.participantroles'),
        ),
        migrations.AddField(
            model_name='collections',
            name='collection_languages',
            field=models.ManyToManyField(blank=True, related_name='collection_languages', to='ailla.languages'),
        ),
        migrations.AddField(
            model_name='collections',
            name='collectors_orgs',
            field=models.ManyToManyField(blank=True, related_name='collectors_orgs', to='ailla.organizations'),
        ),
        migrations.AddField(
            model_name='collections',
            name='collectors_persons',
            field=models.ManyToManyField(blank=True, related_name='collectors_persons', to='ailla.persons'),
        ),
        migrations.AddField(
            model_name='collections',
            name='countries',
            field=models.ManyToManyField(blank=True, to='ailla.countries'),
        ),
        migrations.AddField(
            model_name='collections',
            name='depositors_orgs',
            field=models.ManyToManyField(blank=True, related_name='depositors_orgs', to='ailla.organizations'),
        ),
        migrations.AddField(
            model_name='collections',
            name='depositors_persons',
            field=models.ManyToManyField(blank=True, related_name='depositors_persons', to='ailla.persons'),
        ),
        migrations.AddField(
            model_name='collections',
            name='description',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ailla.text'),
        ),
        migrations.AddField(
            model_name='collections',
            name='lang_indigenous_description',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collection_lang_indigenous_description', to='ailla.languages'),
        ),
        migrations.AddField(
            model_name='collections',
            name='lang_indigenous_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lang_indigenous_title', to='ailla.languages'),
        ),
        migrations.AddField(
            model_name='collections',
            name='title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collection_title', to='ailla.text'),
        ),
        migrations.AddField(
            model_name='collections',
            name='user_last_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserItemRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('EDITOR', 'Editor'), ('VIEWER', 'Viewer')], max_length=6)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ailla.items')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_roles', to='ailla.userprofiles')),
            ],
            options={
                'unique_together': {('user_profile', 'item')},
            },
        ),
        migrations.CreateModel(
            name='UserFolderRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('EDITOR', 'Editor'), ('VIEWER', 'Viewer')], max_length=6)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ailla.folders')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folder_roles', to='ailla.userprofiles')),
            ],
            options={
                'unique_together': {('user_profile', 'folder')},
            },
        ),
        migrations.CreateModel(
            name='UserCollectionRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('EDITOR', 'Editor'), ('VIEWER', 'Viewer')], max_length=6)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ailla.collections')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_roles', to='ailla.userprofiles')),
            ],
            options={
                'unique_together': {('user_profile', 'collection')},
            },
        ),
    ]
